root: /
lib: /lib/
controllers: /controllers/
entities: /controllers/entities/
helpers: /controllers/helpers/
core: /core/
handlers: /handlers/
test: /test/
model: /model/
config: /config/
deployment: /deployment/
providers: /controllers/providers/
tabledefinitions: /deployment/dynamodb/configuration/tables/
seeds: /deployment/dynamodb/configuration/seeds/
analytics: /controllers/analytics/
vendors: /controllers/vendors/
authorizers: /controllers/authorizers/
workers: /controllers/workers/
resources: /resources/
