site:
  name: 'Local SixCRM'
  domain: 'sixcrm.com'

serverless:
  verbose: 2

data_encryption:
  secret_key: 'c6b1249c8e92e30811a6f85e41125469a84d2352be82692af663c1810da77c44'

aws:
  region: 'us-east-1'
  account: ''

lambda:
  region: 'localhost'
  security_group: 'SixCRM-PrivateSubnet'
  subnets:
    - sixcrm-private1
    - sixcrm-private2
    - sixcrm-private3

elasticsearch:
  domain_name: 'sixcrm-logs'
  index_name: 'cloudwatch-logs'

s3:
  account_resources_bucket: 'account-resources'

sts:
  deployment_role_name: 'SixCRMDeployment'

ses:
  hostname: email-smtp.us-east-1.amazonaws.com
  port: 465
  username: 'ses-smtp-user.20170828-134442'
  smtp_username: 'AKIAJEYLHSMCFIJYFMXQ'
  smtp_password: 'AhiiqjfmaJ9M2fD3zhzbjt17Da6xkOpYD2b1bkiovvrm'
  default_sender_email: 'info@development.sixcrm.com'
  default_sender_name: 'Development SixCRM'

jwt:
  issuer: 'https://api.sixcrm.com'
  site: #This is the key for all graph requests (AKA Six users)
    secret_key: 'pO9HJmVXzTOagNP-xW9Es8-s0HGQt28hqlvAPJx6e6rHeryvnyBGDn-LJn_80XdV'
    domain: ''
    expiration: 3600
  transaction: #This is the key for the transactional endpoint requests (AKA non-Six users...)
    secret_key: 'ashdaiuwdaw9d0u197f02ji9ujoja90juahwi'
    expiration: 3600

dynamodb:
  region: 'localhost'
  endpoint: http://local-docker:8000

sqs:
  region: 'localhost'
  deadletter_postfix: '_deadletter'
  max_receive_count: 5
  endpoint: http://local-docker:9324

sns:
  region: 'localhost'
  endpoint: http://local-docker:9911

cloudsearch:
  domainname: 'sixcrm'
  domainendpoint: 'local-docker:15808'

aurora:
  release: 2
  region: 'localhost'
  default_cluster_identifier: 'sixcrm'
  user: 'postgres'
  database: 'postgres'
  password: ''
  host: local-docker
  port: 5440
  max: 10
  idle_timeout: 3000
  randomdata:
    interval: 300

redshift:
  region: 'localhost'
  default_cluster_identifier: 'sixcrm'
  user: 'postgres'
  database: 'postgres'
  password: ''
  host: local-docker
  port: 5440
  max: 10
  idle_timeout: 3000
  randomdata:
    interval: 300

notifications:
  apn:
    token_key: ''
    token_key_id: ''
    token_team_id: ''
    production: false

#Technical Debt:  Down the road, we may have numerous caching strategies and we will need to be able to configure them dynamically
cache:
  usecache: 1
  cachebuster: 'somerandomthing1236901cacdda'

elasticache:
  max_attempts: 3
  retry_time: 1800000
  endpoint: local-docker
  port: 6379
  default_expiration: 300

slack:
  channels:
    - channel: '#lambdas'
      kms_encrypted_hook_url: 'AQECAHj80T7Kli3v5wZmKcPbVFGj7MRHdpLvshzuP2ZIJ3vvjgAAAKcwgaQGCSqGSIb3DQEHBqCBljCBkwIBADCBjQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAyN9XeW0Dk18ZFGQkYCARCAYL6U9hWmdM7Nz+yL0I78O5CU2FPHpzj3/o9yQmpsVaBuSztYipLnam5mlwbfx7mn5cKn8xNyTOD3WGfondnCsVsGyeIVIJJMZs1RWYW3ix18FukLP54LZXctfadN2CcvPQ=='
    - channel: '#servererrors'
      webhook_url: https://hooks.slack.com/services/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

tokenization:
  tokenex:
    id: 2029633460477211
    api_key: XnIOBNQVmQRyfRMiQdA5FuQBalGDDTxWlgoJBL8N
    base: https://test-api.tokenex.com
