version: '3'
services:
  node:
    image: node:8.10
  dynamodb:
    image: cnadiminti/dynamodb-local
    ports:
      - 8000:8000
  redshift:
    image: guildeducation/docker-amazon-redshift
    ports:
      - 5439:5439
  sqs:
    image: vsouza/sqs-local
    ports:
      - 9324:9324
  sns:
    image: s12v/sns
    ports:
      - 9911:9911
  aurora:
    image: circleci/postgres:9.6
    ports:
      - 5440:5432
  cloudsearch:
    image: pallantdigital/nozama-cloudsearch
    ports:
      - 15808:15808
